### ISSUE TITLE
Doesn't work after installation

### ISSUE THREAD

**Issue by uncenteredDiv** [yathavan/eTw-Product-Inquiry#1]
Hi,

I tried to install your extension.
But after i copy all the files to the mage app/ directory I don't see anything in the backend (I mean the Inquiry Tab in the Navigation).
I also can't find the Inquiry Block on the Product Page ...

Firegento Debugger says that there is no config.xml - but there is.

Any idea how I get this working? I'm using Magento 1.9.1.0
I really like the extension - nice and clean.

**Comment by rvpatel** [comment]
I have use magento 1.9.1.0 version with ultimo theme  in local host.
I have display this form ultimo product view page on tab. some correction required for this extension.
i have fix validation class issue and form submission jQuery.
i want how solve admin edit link and product submit issue redirect.

After Submit redirection issue.
Form validation issue.
Admin panel edit link not working properly.

**Comment by mymyhope** [comment]
I changed it to inital capital letter like this:

eTW Inquery     ... this works in windows 
not work on linux hosting

i changed all eTw to Etw,then it works 
Also changed the namespace of Blocks, controllers, Model files and the name of the files all of them has to be intial capitalLetter, all the references in the .xml files aswell.
